# Enables fun features such as a poem in the initial pull request summary. (Options: true, false)
have_fun: false

# Configuration for persistent memory, which is used to improve responses over time.
memory_config:
  # Whether to disable persistent memory for this specific repository. (Options: true, false)
  disabled: tre

# Configuration for code reviews on pull requests.
code_review:
  # Disables Gemini from acting on pull requests completely. (Options: true, false)
  disable: false
  
  # The minimum severity of review comments to consider posting. (Options: LOW, MEDIUM, HIGH, CRITICAL)
  comment_severity_threshold: HIGH
  
  # The maximum number of review comments to post. Use -1 for unlimited. (Options: integer)
  max_review_comments: -1
  
  # Configuration for events triggered when a pull request is opened.
  pull_request_opened:
    # Posts a help message on pull request open. (Options: true, false)
    help: false
    
    # Posts a pull request summary on the pull request open. (Options: true, false)
    summary: false
    
    # Posts a code review on pull request open. (Options: true, false)
    code_review: true
    
    # Enables agent functionality on draft pull requests. (Options: true, false)
    include_drafts: false

# A list of glob patterns for files and directories that Gemini Code Assist should ignore.
ignore_patterns:
  - "*.md"
  - "*.txt"
  - "*.rst"
  - "docs/**"
  - "package-lock.json"
  - "yarn.lock"
  - "build/**"
  - "dist/**"
